services:
  postgres:
    image: postgres:14.0
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
